# -*- mode: ruby -*-
# vi: set ft=ruby :
# Описываем Виртуальные машины
MACHINES = {
  # Указываем имя ВМ "zfs"
  :"zfs" => {
              #Какой vm box будем использовать
              :box_name => "ubuntu2004",
              #Указываем количество ядер ВМ
              :cpus => 2,
              #Указываем количество ОЗУ в мегабайтах
              :memory => 2048,
              :disks => {
                :scsi1 => {
                  :dfile => './sata1.vdi',
                  :size => 550, # Megabytes
                  :port => 1
                },
                :scsi2 => {
                  :dfile => './sata2.vdi',
                  :size => 550,
                  :port => 2
                },
                :scsi3 => {
                  :dfile => './sata3.vdi',
                  :size => 550,
                  :port => 3
                },
                :scsi4 => {
                  :dfile => './sata4.vdi',
                  :size => 550,
                  :port => 4
                },
                :sata5 => {
                  :dfile => './sata5.vdi',
                  :size => 550,
                  :port => 5
                },
                :sata6 => {
                  :dfile => './sata6.vdi',
                  :size => 550,
                  :port => 6
                },
                :sata7 => {
                    :dfile => './sata7.vdi',
                    :size => 550, 
                    :port => 7
                },
                :sata8 => {
                    :dfile => './sata8.vdi',
                    :size => 550, 
                    :port => 8
                },
              }
  },
}

VAGRANT_CONTROLLER_NAME = "Virtual I/O Device SCSI controller"
VAGRANT_CONTROLLER_TYPE = "virtio-scsi"

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    # Отключаем проброс общей папки в ВМ
    # config.vm.synced_folder ".", "/vagrant/ubuntu/", disabled: false
    config.vm.box_check_update = false
    #---
    config.vm.network "public_network", ip: "192.168.100.139", netmask: "255.255.254.0", bridge: "enp6s0"
    #---
    # Применяем конфигурацию ВМ
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      config.vm.box_url = '/root/vagrant/box/ubuntu-jammy.box'
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |vb|
        vb.memory = boxconfig[:memory]
        vb.cpus = boxconfig[:cpus]
        needsController = false
        boxconfig[:disks].each do |_, dconf|
          unless File.exist?(dconf[:dfile])
            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
            needsController =  true
          end
        end
        if needsController == true
          vb.customize ["storagectl", :id, "--name", VAGRANT_CONTROLLER_NAME, "--add", VAGRANT_CONTROLLER_TYPE, '--hostiocache', 'off']
          boxconfig[:disks].each do |_, dconf|
            vb.customize ['storageattach', :id, '--storagectl', VAGRANT_CONTROLLER_NAME, '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
          end
        end
      end
        box.vm.provision "shell", inline: <<-SHELL
            #install zfs
            sudo apt install zfsutils-linux -y
          SHELL
        end
    end
  end
#end
